project:
  type: book
  output-dir: docs

book:
  title: "This is a book"
  author: "Ken Butler"
  date: "2023-01-04"
  chapters:
    - index.qmd
    - hello.qmd
    - computations.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



